services:
  frontend:
    container_name: todo-frontend
    image: todo-front-prod
    build:
      context: ./todo-frontend/
      dockerfile: Dockerfile

  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  redis:
    image: redis
    ports:
      - 6379:6379
    command: [ 'redis-server', '--appendonly', 'yes' ]
    volumes:
      - redis_data:/data

  backend:
    container_name: todo-backend
    image: todo-backend-prod
    build:
      context: ./todo-backend/
      dockerfile: Dockerfile
    volumes:
      - ./todo-backend/:/usr/src/app
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database # ip addr refers to service name
      - REDIS_URL=redis://redis:6379

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro #  the final ro declares that the volume will be read-only
    ports:
      - 8080:80
    container_name: todo-reverse-proxy

volumes:
  mongo_data:
  redis_data: