services:
  app:
    image: hello-front-dev # This will name the image that is being built
    build:
      context: . # The context will pick this directory as the "docker build context"
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3210:3000
    environment:
      - CHOKIDAR_USEPOLLING=true # https://create-react-app.dev/docs/troubleshooting/#npm-start-doesnt-detect-changes
    container_name: hello-front-dev # This will name the container hello-front-dev

  debug-helper:
    image: busybox # this will pull the existing image

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro #  the final ro declares that the volume will be read-only
    ports:
      - 8080:80
    container_name: reverse-proxy