version: '3.8'

services:
  app:
    image: todo-backend
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo-container:27017/the_database
      - REDIS_URL=redis://redis-container:6379
    volumes:
      - ./:/usr/src/app


  mongo:
    container_name: mongo-container
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  redis:
    container_name: redis-container
    image: redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
